# Generated by Django 4.2.4 on 2023-10-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_transaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_type',
            field=models.CharField(choices=[('Visa', 'Visa'), ('Mastercard', 'Mastercard'), ('American_Ixpress', 'American Express'), ('Diners_club_International', 'Diners Club International'), ('JCB_International', 'JCB International'), ('UnionPay_International', 'UnionPay international')], default='Master', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('failed', 'Failed'), ('completed', 'Completed'), ('pending', 'Pending'), ('processing', 'Processing'), ('request_sent', 'Request Sent'), ('request_settled', 'Request Settled'), ('request_processing', 'Request Processing')], default='pending', max_length=100),
        ),
    ]
