# Generated by Django 4.2.4 on 2023-10-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_creditcard_card_type_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_type',
            field=models.CharField(choices=[('Visa', 'Visa'), ('Mastercard', 'Mastercard'), ('American_Express', 'American Express'), ('Diners_club_International', 'Diners Club International'), ('JCB_International', 'JCB International'), ('UnionPay_International', 'UnionPay international')], default='Master', max_length=50),
        ),
    ]
